# Generated by Django 6.0.3 on 2026-04-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='none@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_num',
            field=models.CharField(default='010-0000-0000', max_length=20),
            preserve_default=False,
        ),
    ]
